blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = pagina_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('apps.posts.urls')),
    path('', include('apps.contacto.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('django.contrib.auth.urls')), 
    path('acerca_de/', include('apps.acerca_de.urls')),
    path('productos/', include('productos.urls', namespace='productos')),
    
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from .views import ListaProductosView, DetalleProductoView

app_name = 'productos'

urlpatterns = [
    path('productos/', ListaProductosView.as_view(), name='lista_productos'),
    path('productos/<int:pk>/', DetalleProductoView.as_view(), name='detalle_producto'),
   
]

productos/models.py
from django.db import models

# Create your models here.


class Producto(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='blog\media\productos')
    precio = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
    def __str__(self):
        return self.titulo

productos/views.py
from django.views.generic import ListView, DetailView
from .models import Producto
from django.shortcuts import render
class ListaProductosView(ListView):
    model = Producto
    template_name = 'productos/lista_productos.html'
    context_object_name = 'productos'

class DetalleProductoView(DetailView):
    model = Producto
    template_name = 'productos/detalle_producto.html'
    context_object_name = 'producto'
# En views.py



def index(request):
    productos = Producto.objects.all()
    return render(request, 'base.html', {'productos': productos})

templates/productos/lista_productos.html
{% load static %}

{% block title %}Productos{% endblock %}

{% block contenido %}


    <!-- Carrusel de Productos -->
    <!-- En lista_productos.html para Bootstrap 5 -->
    <div id="carouselProductos" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% for producto in productos %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <div class="card mx-auto" style="max-width: 80vw;">
                        <div class="row g-0">
                            <div class="col-md-12">
                                <img src="{{ producto.imagen.url }}" class="img-fluid" alt="{{ producto.titulo }}" style="width: 100%; height: 80vh; object-fit: cover;">
                            </div>
                            <div class="col-md-12">
                                <div class="card-body">
                                    <h3 class="card-title">{{ producto.titulo }}</h3>
                                   
                                    <a class="dropdown-item" href="{% url 'productos:detalle_producto' producto.pk %}" style="color: green;">Comprar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev btn-dark" type="button" data-bs-target="#carouselProductos" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next btn-dark" type="button" data-bs-target="#carouselProductos" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Siguiente</span>
        </button>
    </div>
    

   
{% endblock %}